export const dataProduct = [
  {
    name: "name 1",
    description: "description 1",
    type: "type 1",
    price: 50,
    id: "1",
  },
  {
    name: "name 2",
    description: "description 2",
    type: "type 2",
    price: 58,
    id: "2",
  },
  {
    name: "name 3",
    description: "description 3",
    type: "type 3",
    price: 18,
    id: "3",
  },
  {
    name: "name 4",
    description: "description 4",
    type: "type 4",
    price: 81,
    id: "4",
  },
  {
    name: "name 5",
    description: "description 5",
    type: "type 5",
    price: 13,
    id: "5",
  },
  {
    name: "name 6",
    description: "description 6",
    type: "type 6",
    price: 24,
    id: "6",
  },
  {
    name: "name 7",
    description: "description 7",
    type: "type 7",
    price: 65,
    id: "7",
  },
  {
    name: "name 8",
    description: "description 8",
    type: "type 8",
    price: 58,
    id: "8",
  },
  {
    name: "name 9",
    description: "description 9",
    type: "type 9",
    price: 46,
    id: "9",
  },
  {
    name: "name 10",
    description: "description 10",
    type: "type 10",
    price: 62,
    id: "10",
  },
  {
    name: "name 11",
    description: "description 11",
    type: "type 11",
    price: 84,
    id: "11",
  },
  {
    name: "name 12",
    description: "description 12",
    type: "type 12",
    price: 99,
    id: "12",
  },
  {
    name: "name 13",
    description: "description 13",
    type: "type 13",
    price: 87,
    id: "13",
  },
  {
    name: "name 14",
    description: "description 14",
    type: "type 14",
    price: 89,
    id: "14",
  },
  {
    name: "name 15",
    description: "description 15",
    type: "type 15",
    price: 73,
    id: "15",
  },
  {
    name: "name 16",
    description: "description 16",
    type: "type 16",
    price: 10,
    id: "16",
  },
  {
    name: "name 17",
    description: "description 17",
    type: "type 17",
    price: 82,
    id: "17",
  },
  {
    name: "name 18",
    description: "description 18",
    type: "type 18",
    price: 33,
    id: "18",
  },
  {
    name: "name 19",
    description: "description 19",
    type: "type 19",
    price: 17,
    id: "19",
  },
  {
    name: "name 20",
    description: "description 20",
    type: "type 20",
    price: 51,
    id: "20",
  },
  {
    name: "name 21",
    description: "description 21",
    type: "type 21",
    price: 38,
    id: "21",
  },
  {
    name: "name 22",
    description: "description 22",
    type: "type 22",
    price: 29,
    id: "22",
  },
  {
    name: "name 23",
    description: "description 23",
    type: "type 23",
    price: 63,
    id: "23",
  },
  {
    name: "name 24",
    description: "description 24",
    type: "type 24",
    price: 33,
    id: "24",
  },
  {
    name: "name 25",
    description: "description 25",
    type: "type 25",
    price: 88,
    id: "25",
  },
  {
    name: "name 26",
    description: "description 26",
    type: "type 26",
    price: 86,
    id: "26",
  },
  {
    name: "name 27",
    description: "description 27",
    type: "type 27",
    price: 10,
    id: "27",
  },
  {
    name: "name 28",
    description: "description 28",
    type: "type 28",
    price: 1,
    id: "28",
  },
];
